# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=40)),
                ('email', models.CharField(db_index=True, max_length=100, unique=True)),
                ('about', models.TextField()),
                ('name', models.CharField(max_length=40)),
                ('isAnonymous', models.BooleanField(default=False)),
            ],
        ),
    ]
